legal_topics = {
    "0": "None",
    "1": "involuntary confession",
    "2": "habeas corpus",
    "3": "plea bargaining: the constitutionality of and/or the circumstances of its exercise",
    "4": "retroactivity (of newly announced or newly enacted constitutional or statutory rights)",
    "5": "search and seizure (other than as pertains to vehicles or Crime Control Act)",
    "6": "search and seizure, vehicles",
    "7": "search and seizure, Crime Control Act",
    "8": "contempt of court or congress",
    "9": "self-incrimination (other than as pertains to Miranda or immunity from prosecution)",
    "10": "Miranda warnings",
    "11": "self-incrimination, immunity from prosecution",
    "12": "right to counsel (cf. indigents appointment of counsel or inadequate representation)",
    "13": "cruel and unusual punishment, death penalty (cf. extra legal jury influence, death penalty)",
    "14": "cruel and unusual punishment, non-death penalty (cf. liability, civil rights acts)",
    "15": "line-up",
    "16": "discovery and inspection (in the context of criminal litigation only, otherwise Freedom of Information Act and related federal or state statutes or regulations)",
    "17": "double jeopardy",
    "18": "ex post facto (state)",
    "19": "extra-legal jury influences: miscellaneous",
    "20": "extra-legal jury influences: prejudicial statements or evidence",
    "21": "extra-legal jury influences: contact with jurors outside courtroom",
    "22": "extra-legal jury influences: jury instructions (not necessarily in criminal cases)",
    "23": "extra-legal jury influences: voir dire (not necessarily a criminal case)",
    "24": "extra-legal jury influences: prison garb or appearance",
    "25": "extra-legal jury influences: jurors and death penalty (cf. cruel and unusual punishment)",
    "26": "extra-legal jury influences: pretrial publicity",
    "27": "confrontation (right to confront accuser, call and cross-examine witnesses)",
    "28": "subconstitutional fair procedure: confession of error",
    "29": "subconstitutional fair procedure: conspiracy (cf. Federal Rules of Criminal Procedure: conspiracy)",
    "30": "subconstitutional fair procedure: entrapment",
    "31": "subconstitutional fair procedure: exhaustion of remedies",
    "32": "subconstitutional fair procedure: fugitive from justice",
    "33": "subconstitutional fair procedure: presentation, admissibility, or sufficiency of evidence (not necessarily a criminal case)",
    "34": "subconstitutional fair procedure: stay of execution",
    "35": "subconstitutional fair procedure: timeliness",
    "36": "subconstitutional fair procedure: miscellaneous",
    "37": "Federal Rules of Criminal Procedure",
    "38": "statutory construction of criminal laws: assault",
    "39": "statutory construction of criminal laws: bank robbery",
    "40": "statutory construction of criminal laws: conspiracy (cf. subconstitutional fair procedure: conspiracy)",
    "41": "statutory construction of criminal laws: escape from custody",
    "42": "statutory construction of criminal laws: false statements (cf. statutory construction of criminal laws: perjury)",
    "43": "statutory construction of criminal laws: financial (other than in fraud or internal revenue)",
    "44": "statutory construction of criminal laws: firearms",
    "45": "statutory construction of criminal laws: fraud",
    "46": "statutory construction of criminal laws: gambling",
    "47": "statutory construction of criminal laws: Hobbs Act; i.e., 18 USC 1951",
    "48": "statutory construction of criminal laws: immigration (cf. immigration and naturalization)",
    "49": "statutory construction of criminal laws: internal revenue (cf. Federal Taxation)",
    "50": "statutory construction of criminal laws: Mann Act and related statutes",
    "51": "statutory construction of criminal laws: narcotics includes regulation and prohibition of alcohol",
    "52": "statutory construction of criminal laws: obstruction of justice",
    "53": "statutory construction of criminal laws: perjury (other than as pertains to statutory construction of criminal laws: false statements)",
    "54": "statutory construction of criminal laws: Travel Act, 18 USC 1952",
    "55": "statutory construction of criminal laws: war crimes",
    "56": "statutory construction of criminal laws: sentencing guidelines",
    "57": "statutory construction of criminal laws: miscellaneous",
    "58": "jury trial (right to, as distinct from extra-legal jury influences)",
    "59": "speedy trial",
    "60": "miscellaneous criminal procedure (cf. due process, prisoners' rights, comity: criminal procedure)",
    "61": "voting",
    "62": "Voting Rights Act of 1965, plus amendments",
    "63": "ballot access (of candidates and political parties)",
    "64": "desegregation (other than as pertains to school desegregation, employment discrimination, and affirmative action)",
    "65": "desegregation, schools",
    "66": "employment discrimination: on basis of race, age, religion, illegitimacy, national origin, or working conditions.",
    "67": "affirmative action",
    "68": "slavery or indenture",
    "69": "sit-in demonstrations (protests against racial discrimination in places of public accommodation)",
    "70": "reapportionment: other than plans governed by the Voting Rights Act",
    "71": "debtors' rights",
    "72": "deportation (cf. immigration and naturalization)",
    "73": "employability of aliens (cf. immigration and naturalization)",
    "74": "sex discrimination (excluding sex discrimination in employment)",
    "75": "sex discrimination in employment (cf. sex discrimination)",
    "76": "Indians (other than pertains to state jurisdiction over)",
    "77": "Indians, state jurisdiction over",
    "78": "juveniles (cf. rights of illegitimates)",
    "79": "poverty law, constitutional",
    "80": "poverty law, statutory: welfare benefits, typically under some Social Security Act provision.",
    "81": "illegitimates, rights of (cf. juveniles): typically inheritance and survivor's benefits, and paternity suits",
    "82": "handicapped, rights of: under Rehabilitation, Americans with Disabilities Act, and related statutes",
    "83": "residency requirements: durational, plus discrimination against nonresidents",
    "84": "military: draftee, or person subject to induction",
    "85": "military: active duty",
    "86": "military: veteran",
    "87": "immigration and naturalization: permanent residence",
    "88": "immigration and naturalization: citizenship",
    "89": "immigration and naturalization: loss of citizenship, denaturalization",
    "90": "immigration and naturalization: access to public education",
    "91": "immigration and naturalization: welfare benefits",
    "92": "immigration and naturalization: miscellaneous",
    "93": "indigents: appointment of counsel (cf. right to counsel)",
    "94": "indigents: inadequate representation by counsel (cf. right to counsel)",
    "95": "indigents: payment of fine",
    "96": "indigents: costs or filing fees",
    "97": "indigents: U.S. Supreme Court docketing fee",
    "98": "indigents: transcript",
    "99": "indigents: assistance of psychiatrist",
    "100": "indigents: miscellaneous",
    "101": "liability, civil rights acts (cf. liability, governmental and liability, nongovernmental; cruel and unusual punishment, non-death penalty)",
    "102": "miscellaneous civil rights (cf. comity: civil rights)",
    "103": "First Amendment, miscellaneous (cf. comity: First Amendment)",
    "104": "commercial speech, excluding attorneys",
    "105": "libel, defamation: defamation of public officials and public and private persons",
    "106": "libel, privacy: true and false light invasions of privacy",
    "107": "legislative investigations: concerning internal security only",
    "108": "federal or state internal security legislation: Smith, Internal Security, and related federal statutes",
    "109": "loyalty oath or non-Communist affidavit (other than bar applicants, government employees, political party, or teacher)",
    "110": "loyalty oath: bar applicants (cf. admission to bar, state or federal or U.S. Supreme Court)",
    "111": "loyalty oath: government employees",
    "112": "loyalty oath: political party",
    "113": "loyalty oath: teachers",
    "114": "security risks: denial of benefits or dismissal of employees for reasons other than failure to meet loyalty oath requirements",
    "115": "conscientious objectors (cf. military draftee or military active duty) to military service",
    "116": "campaign spending (cf. governmental corruption):",
    "117": "protest demonstrations (other than as pertains to sit-in demonstrations): demonstrations and other forms of protest based on First Amendment guarantees",
    "118": "free exercise of religion",
    "119": "establishment of religion (other than as pertains to parochiaid:)",
    "120": "parochiaid: government aid to religious schools, or religious requirements in public schools",
    "121": "obscenity, state (cf. comity: privacy): including the regulation of sexually explicit material under the 21st Amendment",
    "122": "obscenity, federal",
    "123": "due process: miscellaneous (cf. loyalty oath), the residual code",
    "124": "due process: hearing or notice (other than as pertains to government employees or prisoners' rights)",
    "125": "due process: hearing, government employees",
    "126": "due process: prisoners' rights and defendants' rights",
    "127": "due process: impartial decision maker",
    "128": "due process: jurisdiction (jurisdiction over non-resident litigants)",
    "129": "due process: takings clause, or other non-constitutional governmental taking of property",
    "130": "privacy (cf. libel, comity: privacy)",
    "131": "abortion: including contraceptives",
    "132": "right to die",
    "133": "Freedom of Information Act and related federal or state statutes or regulations",
    "134": "attorneys' and governmental employees' or officials' fees or compensation or licenses",
    "135": "commercial speech, attorneys (cf. commercial speech)",
    "136": "admission to a state or federal bar, disbarment, and attorney discipline (cf. loyalty oath: bar applicants)",
    "137": "admission to, or disbarment from, Bar of the U.S. Supreme Court",
    "138": "arbitration (in the context of labor-management or employer-employee relations) (cf. arbitration)",
    "139": "union antitrust: legality of anticompetitive union activity",
    "140": "union or closed shop: includes agency shop litigation",
    "141": "Fair Labor Standards Act",
    "142": "Occupational Safety and Health Act",
    "143": "union-union member dispute (except as pertains to union or closed shop)",
    "144": "labor-management disputes: bargaining",
    "145": "labor-management disputes: employee discharge",
    "146": "labor-management disputes: distribution of union literature",
    "147": "labor-management disputes: representative election",
    "148": "labor-management disputes: antistrike injunction",
    "149": "labor-management disputes: jurisdictional dispute",
    "150": "labor-management disputes: right to organize",
    "151": "labor-management disputes: picketing",
    "152": "labor-management disputes: secondary activity",
    "153": "labor-management disputes: no-strike clause",
    "154": "labor-management disputes: union representatives",
    "155": "labor-management disputes: union trust funds (cf. ERISA)",
    "156": "labor-management disputes: working conditions",
    "157": "labor-management disputes: miscellaneous dispute",
    "158": "miscellaneous union",
    "159": "antitrust (except in the context of mergers and union antitrust)",
    "160": "mergers",
    "161": "bankruptcy (except in the context of priority of federal fiscal claims)",
    "162": "sufficiency of evidence: typically in the context of a jury's determination of compensation for injury or death",
    "163": "election of remedies: legal remedies available to injured persons or things",
    "164": "liability, governmental: tort or contract actions by or against government or governmental officials other than defense of criminal actions brought under a civil rights action.",
    "165": "liability, other than as in sufficiency of evidence, election of remedies, punitive damages",
    "166": "liability, punitive damages",
    "167": "Employee Retirement Income Security Act (cf. union trust funds)",
    "168": "state or local government tax",
    "169": "state and territorial land claims",
    "170": "state or local government regulation, especially of business (cf. federal pre-emption of state court jurisdiction, federal pre-emption of state legislation or regulation)",
    "171": "federal or state regulation of securities",
    "172": "natural resources - environmental protection (cf. national supremacy: natural resources, national supremacy: pollution)",
    "173": "corruption, governmental or governmental regulation of other than as in campaign spending",
    "174": "zoning: constitutionality of such ordinances, or restrictions on owners' or lessors' use of real property",
    "175": "arbitration (other than as pertains to labor-management or employeremployee relations (cf. union arbitration)",
    "176": "federal or state consumer protection: typically under the Truth in Lending; Food, Drug and Cosmetic; and Consumer Protection Credit Acts",
    "177": "patents and copyrights: patent",
    "178": "patents and copyrights: copyright",
    "179": "patents and copyrights: trademark",
    "180": "patents and copyrights: patentability of computer processes",
    "181": "federal or state regulation of transportation regulation: railroad",
    "182": "federal and some few state regulations of transportation regulation: boat",
    "183": "federal and some few state regulation of transportation regulation:truck, or motor carrier",
    "184": "federal and some few state regulation of transportation regulation: pipeline (cf. federal public utilities regulation: gas pipeline)",
    "185": "federal and some few state regulation of transportation regulation: airline",
    "186": "federal and some few state regulation of public utilities regulation: electric power",
    "187": "federal and some few state regulation of public utilities regulation: nuclear power",
    "188": "federal and some few state regulation of public utilities regulation: oil producer",
    "189": "federal and some few state regulation of public utilities regulation: gas producer",
    "190": "federal and some few state regulation of public utilities regulation: gas pipeline (cf. federal transportation regulation: pipeline)",
    "191": "federal and some few state regulation of public utilities regulation: radio and television (cf. cable television)",
    "192": "federal and some few state regulation of public utilities regulation: cable television (cf. radio and television)",
    "193": "federal and some few state regulations of public utilities regulation: telephone or telegraph company",
    "194": "miscellaneous economic regulation",
    "195": "comity: civil rights",
    "196": "comity: criminal procedure",
    "197": "comity: First Amendment",
    "198": "comity: habeas corpus",
    "199": "comity: military",
    "200": "comity: obscenity",
    "201": "comity: privacy",
    "202": "comity: miscellaneous",
    "203": "comity primarily removal cases, civil procedure (cf. comity, criminal and First Amendment); deference to foreign judicial tribunals",
    "204": "assessment of costs or damages: as part of a court order",
    "205": "Federal Rules of Civil Procedure including Supreme Court Rules, application of the Federal Rules of Evidence, Federal Rules of Appellate Procedure in civil litigation, Circuit Court Rules, and state rules and admiralty rules",
    "206": "judicial review of administrative agency's or administrative official's actions and procedures",
    "207": "mootness (cf. standing to sue: live dispute)",
    "208": "venue",
    "209": "no merits: writ improvidently granted",
    "210": "no merits: dismissed or affirmed for want of a substantial or properly presented federal question, or a nonsuit",
    "211": "no merits: dismissed or affirmed for want of jurisdiction (cf. judicial administration: Supreme Court jurisdiction or authority on appeal from federal district courts or courts of appeals)",
    "212": "no merits: adequate non-federal grounds for decision",
    "213": "no merits: remand to determine basis of state or federal court decision (cf. judicial administration: state law)",
    "214": "no merits: miscellaneous",
    "215": "standing to sue: adversary parties",
    "216": "standing to sue: direct injury",
    "217": "standing to sue: legal injury",
    "218": "standing to sue: personal injury",
    "219": "standing to sue: justiciable question",
    "220": "standing to sue: live dispute",
    "221": "standing to sue: parens patriae standing",
    "222": "standing to sue: statutory standing",
    "223": "standing to sue: private or implied cause of action",
    "224": "standing to sue: taxpayer's suit",
    "225": "standing to sue: miscellaneous",
    "226": "judicial administration: jurisdiction or authority of federal district courts or territorial courts",
    "227": "judicial administration: jurisdiction or authority of federal courts of appeals",
    "228": "judicial administration: Supreme Court jurisdiction or authority on appeal or writ of error, from federal district courts or courts of appeals (cf. 753)",
    "229": "judicial administration: Supreme Court jurisdiction or authority on appeal or writ of error, from highest state court",
    "230": "judicial administration: jurisdiction or authority of the Court of Claims",
    "231": "judicial administration: Supreme Court's original jurisdiction",
    "232": "judicial administration: review of non-final order",
    "233": "judicial administration: change in state law (cf. no merits: remand to determine basis of state court decision)",
    "234": "judicial administration: federal question (cf. no merits: dismissed for want of a substantial or properly presented federal question)",
    "235": "judicial administration: ancillary or pendent jurisdiction",
    "236": "judicial administration: extraordinary relief (e.g., mandamus, injunction)",
    "237": "judicial administration: certification (cf. objection to reason for denial of certiorari or appeal)",
    "238": "judicial administration: resolution of circuit conflict, or conflict between or among other courts",
    "239": "judicial administration: objection to reason for denial of certiorari or appeal",
    "240": "judicial administration: collateral estoppel or res judicata",
    "241": "judicial administration: interpleader",
    "242": "judicial administration: untimely filing",
    "243": "judicial administration: Act of State doctrine",
    "244": "judicial administration: miscellaneous",
    "245": "Supreme Court's certiorari, writ of error, or appeals jurisdiction",
    "246": "miscellaneous judicial power, especially diversity jurisdiction",
    "247": "federal-state ownership dispute (cf. Submerged Lands Act)",
    "248": "federal pre-emption of state court jurisdiction",
    "249": "federal pre-emption of state legislation or regulation. cf. state regulation of business. rarely involves union activity. Does not involve constitutional interpretation unless the Court says it does.",
    "250": "Submerged Lands Act (cf. federal-state ownership dispute)",
    "251": "national supremacy: commodities",
    "252": "national supremacy: intergovernmental tax immunity",
    "253": "national supremacy: marital and family relationships and property, including obligation of child support",
    "254": "national supremacy: natural resources (cf. natural resources - environmental protection)",
    "255": "national supremacy: pollution, air or water (cf. natural resources environmental protection)",
    "256": "national supremacy: public utilities (cf. federal public utilities regulation)",
    "257": "national supremacy: state tax (cf. state tax)",
    "258": "national supremacy: miscellaneous",
    "259": "miscellaneous federalism",
    "260": "boundary dispute between states",
    "261": "non-real property dispute between states",
    "262": "miscellaneous interstate relations conflict",
    "263": "incorporation of foreign territories",
    "264": "federal taxation, typically under provisions of the Internal Revenue Code",
    "265": "federal taxation of gifts, personal, business, or professional expenses",
    "266": "priority of federal fiscal claims: over those of the states or private entities",
    "267": "miscellaneous federal taxation (cf. national supremacy: state tax)",
    "268": "legislative veto",
    "269": "executive authority vis-a-vis congress or the states",
    "270": "miscellaneous",
    "271": "real property",
    "272": "personal property",
    "273": "contracts",
    "274": "evidence",
    "275": "civil procedure",
    "276": "torts",
    "277": "wills and trusts",
    "278": "commercial transactions"
} 